### ISSUE TITLE
Floating Tools not loading

### ISSUE THREAD

**Issue by Eharper07** [aldmbmtl/FloatingTools#1]
On my current set up (Windows 10 with non commercial Nuke) I am unable to get Floating tools to load properly.  When running the import FloatingTools command in the script editor I get the following response:

import FloatingTools
# Result: C:\Users\Eric\.nuke\FloatingTools\packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Users\Eric\.nuke\FloatingTools\packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in c:\users\eric\.nuke\floatingtools\packages
Install is up-to-date.
Application does not support multi-threaded load up.
Loading Repository: aldmbmtl/toolbox
/tools/Generic is not a valid path in this toolbox.

**Comment by aldmbmtl** [comment]
All taken care of. Roll to release 0.5.50
